pipeline:
  name: Build boilerjuice-tank-api
  identifier: Build_boilerjuice_tank_api_1760365293718
  projectIdentifier: testcdapp
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Test
                  identifier: Echo_Test
                  spec:
                    connectorRef: InternalDHProxy
                    image: busybox:latest
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: harnessk8sconnector
              namespace: harness-builds
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
  properties:
    ci:
      codebase:
        connectorRef: harnessgitconnector
        repoName: boilerjuice-tank-api
        build: <+input>
